### ISSUE TITLE
feat: 期望实现【头像戳一戳】事件

### ISSUE THREAD

**Issue by SlightDust** [linxinrao/Shamrock#108]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

支持头像戳一戳事件

### 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

**Comment by SlightDust** [comment]
主动发送touch消息的话，对方能正常收到戳一戳，nonebot会抛出
```python
[2023-10-15 15:56:41,772 my_chat] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when zaine handling message 1792658311.
[2023-10-15 15:56:41,772 my_chat] ERROR: <ActionFailed status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo={'seq': 1}>
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "/root/qqbot/HoshinoBot/hoshino/modules/my_chat/my_chat.py", line 106, in zaine
    await bot.send(ev, poke)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo={'seq': 1}>
```
sr日志报
```[16:07:11] WARN java.lang.IllegalStateException: Instance is not ProtoMap
	at moe.fuqiuluo.proto.ProtoValue$DefaultImpls.get(ProtoValue.kt:34)
	at moe.fuqiuluo.proto.ProtoByteString.get(ProtoByteString.kt:9)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener.onGroupPoke(PrimitiveListener.kt:76)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener.onMsgPush(PrimitiveListener.kt:62)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener.access$onMsgPush(PrimitiveListener.kt:29)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener$registerListener$1$1.invokeSuspend(PrimitiveListener.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[16:07:12] WARN 不支持的提示类型: GrayTipElement{subElementType=12,revokeElement=null,proclamationElement=null,emojiReplyElement=null,groupElement=null,buddyElement=null,feedMsgElement=null,essenceElement=null,groupNotifyElement=null,buddyNotifyElement=null,xmlElement=XmlElement{busiType=12,busiId=1061,c2cType=0,serviceType=0,ctrlFlag=7,content=<gtip align="center"> <qq uin="xxxxxxxxx" col="1" nm="" /> <img src="http://tianquan.gtimg.cn/nudgeaction/item/1/expression.jpg" jp="https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2&amp;actionId=1" /> <nor txt="拍了拍"/> <qq uin="xxxxxxxxx-NQ" col="1" nm="" tp="0"/> <nor txt="的赛博木鱼，公德+1"/> </gtip>,templId=1132,seqId=750405651,templParam={type_str2=0, uin_str1=xxxxxxxx, uin_str2=xxxxxxxx, jp_str1=https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2&amp;actionId=1, action_img_url=http://tianquan.gtimg.cn/nudgeaction/item/1/expression.jpg, action_str=拍了拍, nick_str2=, suffix_str=的赛博木鱼，公德+1, nick_str1=},pbReserv=null,members={xxxxxxxxx=xxxxxxxx, xxxxxxxxx=xxxxxxxx},},fileReceiptElement=null,localGrayTipElement=null,blockGrayTipElement=null,aioOpGrayTipElement=null,jsonGrayTipElement=null,walletGrayTipElement=null,}
```
应该也是不支持头像戳一戳事件导致的

**Comment by fuqiuluo** [comment]
预计实现时间：12h
当然任务排序：群文件功能后

**Comment by fuqiuluo** [comment]
已经修复主动戳一戳消息提示合成失败了，看最新actions，事件推送大概会在今天晚上完成。

**Comment by SlightDust** [comment]
主动戳一戳验证ok

**Comment by fuqiuluo** [comment]
您的头像戳一戳事件是怎么触发的呢？

**Comment by SlightDust** [comment]
就是在移动端双击头像

**Comment by fuqiuluo** [comment]
![image](https://github.com/linxinrao/Shamrock/assets/61898844/9f822acd-821e-4436-b9da-b4ad50f3672a)

**Comment by fuqiuluo** [comment]
戳一戳有实现？（

**Comment by RealHeart** [comment]
> 戳一戳有实现？（

有

**Comment by RealHeart** [comment]
> 戳一戳有实现？（

不过私聊没有

**Comment by fuqiuluo** [comment]
私聊也有好像，那个解析逻辑有问题

**Comment by fuqiuluo** [comment]
已经修了，不过我要去跑步了，所以说等一下再提交

**Comment by fuqiuluo** [comment]
在最新构建修复了，部分群聊无法触发戳一戳的问题

**Comment by SlightDust** [comment]
group_id的上报好像有些问题？

**Comment by SlightDust** [comment]
在三个群测试了一下，左边是实际的群号，右边是上报的群号  
209677708 -> 2196777087  
276196898 -> 4166196898  
100707002 -> 2043707002

**Comment by SlightDust** [comment]
今天先休息了，辛苦大佬！

**Comment by SlightDust** [comment]
dev.26395e5  群号还是和之前一样的问题...
```
[13:54:33] INFO 群消息(group = 测试用<$ÿĀ>(100707002), uin = 1085289815, id = 1773505691, msg = 啊)
[13:54:38] INFO 群戳一戳(2043707002): 1085289815 -> 2471737329
```

**Comment by SlightDust** [comment]
d868932验证ok
