### ISSUE TITLE
[BUG] WebSocket call api `get_msg` timeout in nonebot-adapter-onebot-v11

### ISSUE THREAD

**Issue by djkcyl** [linxinrao/Shamrock#41]
**Describe the bug**
```
2023-10-03 01:32:32.190 | WARNING  | nonebot:log:261 - OneBot V11 | Error when getting message reply info: NetWorkError(message='WebSocket call api get_msg timeout')
Traceback (most recent call last):

  File "/home/admin/bots/SneakyBot/bot.py", line 32, in <module>
    nonebot.run()
    │       └ <function run at 0x7fd7d8010cc0>
    └ <module 'nonebot' from '/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py'>

  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fd7d8a1f7e0>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
    │       └ <function run at 0x7fd7d7b75300>
    └ <module 'uvicorn' from '/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/__init__.py'>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7fd7d7b76ac0>
    └ <uvicorn.server.Server object at 0x7fd7cff59490>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fd7d7b76b60>
           │       │   └ <uvicorn.server.Server object at 0x7fd7cff59490>
           │       └ <function run at 0x7fd7d8fe7f60>
           └ <module 'asyncio' from '/usr/lib/python3.11/asyncio/__init__.py'>
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7fd7d481f560>
           │      └ <function Runner.run at 0x7fd7d8ad1260>
           └ <asyncio.runners.Runner object at 0x7fd7d66aba10>
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-4' coro=<Server.serve() running at /home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvi...
           │    │     └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7fd7d66aba10>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/bot.py", line 190, in handle_event
    await _check_reply(self, event)
          │            │     └ GroupMessageEvent(time=1696267921, self_id=1070330078, post_type='message', sub_type='normal', user_id=1372362033, message_ty...
          │            └ Bot(type='OneBot V11', self_id='1070330078')
          └ <function _check_reply at 0x7fd7d7fa07c0>
> File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/bot.py", line 34, in _check_reply
    event.reply = Reply.parse_obj(await bot.get_msg(message_id=msg_seg.data["id"]))
    │     │       │     │               │                      │       └ {'id': 3181547}
    │     │       │     │               │                      └ MessageSegment(type='reply', data={'id': 3181547})
    │     │       │     │               └ Bot(type='OneBot V11', self_id='1070330078')
    │     │       │     └ <classmethod(<cyfunction BaseModel.parse_obj at 0x7fd7d86c4450>)>
    │     │       └ <class 'nonebot.adapters.onebot.v11.event.Reply'>
    │     └ None
    └ GroupMessageEvent(time=1696267921, self_id=1070330078, post_type='message', sub_type='normal', user_id=1372362033, message_ty...
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
          └ NetWorkError(message='WebSocket call api get_msg timeout')
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'message_id': 3181547}
                   │    │       │         │     └ 'get_msg'
                   │    │       │         └ Bot(type='OneBot V11', self_id='1070330078')
                   │    │       └ <function Adapter._call_api at 0x7fd7d7fa3600>
                   │    └ Adapter(name='OneBot V11')
                   └ Bot(type='OneBot V11', self_id='1070330078')
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 145, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
          └ <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>

nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api get_msg timeout')
```

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 LTS

**Smartphone (please complete the following information):**
 - Device: Redmi K50
 - OS: MIUI13(android 12)

**Comment by fuqiuluo** [comment]
无法复现
