### ISSUE TITLE
[BUG] ws 心跳包缺少字段导致 Nonebot 结构体校验错误

### ISSUE THREAD

**Issue by djkcyl** [linxinrao/Shamrock#42]
**To Reproduce**
使用 [CI版](https://github.com/linxinrao/Shamrock/actions/runs/6372858625) 及以后的版本 连接成功后 收到心跳包在 `Nonebot` 内会结构体不完整，缺少字段

最新的 Release 版本未发现此问题

**Describe the bug**
```
2023-10-03 02:45:43.388 | DEBUG    | nonebot:log:261 - OneBot V11 | Event Parser Error
Traceback (most recent call last):

  File "/home/admin/bots/SneakyBot/bot.py", line 32, in <module>
    nonebot.run()
    │       └ <function run at 0x7f1799464cc0>
    └ <module 'nonebot' from '/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py'>

  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f1799e777e0>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
    │       └ <function run at 0x7f1798fc5300>
    └ <module 'uvicorn' from '/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/__init__.py'>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7f1798fc6ac0>
    └ <uvicorn.server.Server object at 0x7f1797c97490>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f1798fc6b60>
           │       │   └ <uvicorn.server.Server object at 0x7f1797c97490>
           │       └ <function run at 0x7f179a43bf60>
           └ <module 'asyncio' from '/usr/lib/python3.11/asyncio/__init__.py'>
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7f1795c7b560>
           │      └ <function Runner.run at 0x7f1799f25260>
           └ <asyncio.runners.Runner object at 0x7f1795cdba90>
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-4' coro=<Server.serve() running at /home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvi...
           │    │     └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7f1795cdba90>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
                   │    │   │    │      │    │             │    └ <function WebSocketProtocol.asgi_send at 0x7f17954aec00>
                   │    │   │    │      │    │             └ <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f1794f98610>
                   │    │   │    │      │    └ <function WebSocketProtocol.asgi_receive at 0x7f17954aeca0>
                   │    │   │    │      └ <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f1794f98610>
                   │    │   │    └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
                   │    │   └ <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f1794f98610>
                   │    └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f1795468ad0>
                   └ <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f1794f98610>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method WebSocketProtocol.asgi_send of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f17...
                 │    │   │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
                 │    │   └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
                 │    └ <fastapi.applications.FastAPI object at 0x7f17988daa50>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f1795468ad0>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method WebSocketProtocol.asgi_send of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f17...
                           │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
                           └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method WebSocketProtocol.asgi_send of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f17...
          │    │                │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
          │    │                └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f17954b7410>
          └ <fastapi.applications.FastAPI object at 0x7f17988daa50>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method WebSocketProtocol.asgi_send of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7f17...
          │    │   │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
          │    │   └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f17954b7890>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f17954b7410>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f1794fd7b00>
          │    │   │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
          │    │   └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f17954b7050>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f17954b7890>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f1794fd7b00>
          │    │   │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
          │    │   └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
          │    └ <fastapi.routing.APIRouter object at 0x7f1799accb50>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f17954b7050>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f1794fd7b00>
          │     │      │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
          │     │      └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
          │     └ <function WebSocketRoute.handle at 0x7f1798b698a0>
          └ APIWebSocketRoute(path='/onebot/v11/', name='OneBot V11 Root WS')
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f1794fd7b00>
          │    │   │      └ <bound method WebSocketProtocol.asgi_receive of <uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol object at 0x7...
          │    │   └ {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('1...
          │    └ <function websocket_session.<locals>.app at 0x7f1798792840>
          └ APIWebSocketRoute(path='/onebot/v11/', name='OneBot V11 Root WS')
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/starlette/routing.py", line 82, in app
    await func(session)
          │    └ <starlette.websockets.WebSocket object at 0x7f1797c7d5d0>
          └ <function get_websocket_app.<locals>.app at 0x7f17987928e0>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
          │         │      └ {'websocket': <starlette.websockets.WebSocket object at 0x7f1797c7d5d0>}
          │         └ <function Driver.setup_websocket_server.<locals>._handle at 0x7f1798792700>
          └ <fastapi.dependencies.models.Dependant object at 0x7f1798796d90>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 150, in _handle
    await self._handle_ws(websocket, setup)
          │    │          │          └ WebSocketServerSetup(path=URL('/onebot/v11/'), name='OneBot V11 Root WS', handle_func=<bound method Adapter._handle_ws of Ada...
          │    │          └ <starlette.websockets.WebSocket object at 0x7f1797c7d5d0>
          │    └ <function Driver._handle_ws at 0x7f1798ba8ae0>
          └ Driver(type='fastapi+httpx+websockets', adapters=2, bots=1)
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 267, in _handle_ws
    await setup.handle_func(ws)
          │     │           └ FastAPIWebSocket('ws://ali.well404.top:40094/onebot/v11/')
          │     └ <bound method Adapter._handle_ws of Adapter(name='OneBot V11')>
          └ WebSocketServerSetup(path=URL('/onebot/v11/'), name='OneBot V11 Root WS', handle_func=<bound method Adapter._handle_ws of Ada...
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 244, in _handle_ws
    if event := self.json_to_event(json_data):
       │        │    │             └ {'time': 1696272343, 'self_id': 1070330078, 'post_type': 'meta_event', 'meta_event_type': 'heartbeat', 'sub_type': 'connect'}
       │        │    └ <classmethod(<function Adapter.json_to_event at 0x7f17993f3c40>)>
       │        └ Adapter(name='OneBot V11')
       └ MetaEvent(time=1696272338, self_id=1070330078, post_type='meta_event', meta_event_type='heartbeat', sub_type='connect')
> File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 426, in json_to_event
    event = model.parse_obj(json_data)
            │     │         └ {'time': 1696272343, 'self_id': 1070330078, 'post_type': 'meta_event', 'meta_event_type': 'heartbeat', 'sub_type': 'connect'}
            │     └ <classmethod(<cyfunction BaseModel.parse_obj at 0x7f1799b1c450>)>
            └ <class 'nonebot.adapters.onebot.v11.event.HeartbeatMetaEvent'>

  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)

  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error

pydantic.error_wrappers.ValidationError: 2 validation errors for HeartbeatMetaEvent
status
  field required (type=value_error.missing)
interval
  field required (type=value_error.missing)
```

**Screenshots**
![7d6b598a2b9815dcc02222318a8c2c5b](https://github.com/linxinrao/Shamrock/assets/59153990/8e10ed78-9a99-4555-88b6-8fb7ebcafcde)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 LTS

**Smartphone (please complete the following information):**
 - Device: Redmi K50
 - OS: MIUI13(android 12)

**Comment by fuqiuluo** [comment]
已提交代码，看最新构建，测试

**Comment by djkcyl** [comment]
![image](https://github.com/linxinrao/Shamrock/assets/59153990/45af8c09-8e02-48ea-917e-6ddcfe200ecc)
貌似还未解决
