### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by zhongwen-4** [linxinrao/Shamrock#46]
报错日志
[15:48:48] ERROR java.net.URISyntaxException: Expected authority at index 5: ws://
	at java.net.URI$Parser.fail(URI.java:2893)
	at java.net.URI$Parser.failExpecting(URI.java:2899)
	at java.net.URI$Parser.parseHierarchical(URI.java:3147)
	at java.net.URI$Parser.parse(URI.java:3098)
	at java.net.URI.<init>(URI.java:584)
	at moe.fuqiuluo.remote.WebSocketClient.<init>(WebSocketClient.kt:25)
	at moe.fuqiuluo.xposed.actions.InitRemoteService$startWebSocketClient$1.invokeSuspend(InitRemoteService.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by fuqiuluo** [comment]
配置界面截图看看

**Comment by zhongwen-4** [comment]
> 配置界面截图看看

![Uploading Screenshot_2023-10-04-16-10-09-771_moe.fuqiuluo.shamrock.jpg…]()

**Comment by zhongwen-4** [comment]
> 配置界面截图看看

![Screenshot_2023-10-04-16-10-09-771_moe fuqiuluo shamrock](https://github.com/linxinrao/Shamrock/assets/114509415/a3ec5746-bda8-4e62-88dc-ef36c8dec8f7)

**Comment by zhongwen-4** [comment]
> > 配置界面截图看看
> 
> ![Screenshot_2023-10-04-16-10-09-771_moe fuqiuluo shamrock](https://user-images.githubusercontent.com/114509415/272506462-a3ec5746-bda8-4e62-88dc-ef36c8dec8f7.jpg)

全部关了也依旧报错

**Comment by fuqiuluo** [comment]
shamrock作为客户端(被动)错误了，因为shamrock.moe:81是一个虚假的地址，是连不上的，请关闭被动WebSocket开关

**Comment by zhongwen-4** [comment]
> shamrock作为客户端(被动)错误了，因为shamrock.moe:81是一个虚假的地址，是连不上的，请关闭被动WebSocket开关

那也就是说弄个真的地址就好了吧，我弄个内网穿透看看()
