### ISSUE TITLE
[BUG] `get_msg` API 不可用

### ISSUE THREAD

**Issue by Well2333** [linxinrao/Shamrock#55]
可以确认原消息在shamrock是启动后发出的
```
2023-10-10 13:27:12.887 | SUCCESS  | nonebot:handle_event:497 - OneBot V11 1070330078 | [message.group.normal]: Message 1531956124 from 1943125575@[群:xxxxx] '123'
```
但通过 `get_msg` 获取该消息内容依旧会出问题
```
2023-10-10 13:27:38.414 | WARNING  | nonebot:log:261 - OneBot V11 | Error when getting message reply info: ActionFailed(status='failed', retcode=35000, data={}, message='Obtain msg failed, please check your msg_id.', echo='41')
Traceback (most recent call last):

  File "/home/admin/bots/SneakyBot/bot.py", line 32, in <module>
    nonebot.run()
    │       └ <function run at 0x7ff10411ccc0>
    └ <module 'nonebot' from '/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py'>

  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7ff104b377e0>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
    │       └ <function run at 0x7ff103c85300>
    └ <module 'uvicorn' from '/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/__init__.py'>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7ff103c86ac0>
    └ <uvicorn.server.Server object at 0x7ff100f864d0>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7ff103c86b60>
           │       │   └ <uvicorn.server.Server object at 0x7ff100f864d0>
           │       └ <function run at 0x7ff1050fbf60>
           └ <module 'asyncio' from '/usr/lib/python3.11/asyncio/__init__.py'>
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7ff1015e1360>
           │      └ <function Runner.run at 0x7ff104be9260>
           └ <asyncio.runners.Runner object at 0x7ff10179bd90>
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-4' coro=<Server.serve() running at /home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/uvi...
           │    │     └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7ff10179bd90>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/bot.py", line 190, in handle_event
    await _check_reply(self, event)
          │            │     └ GroupMessageEvent(time=1696915658, self_id=1070330078, post_type='message', sub_type='normal', user_id=1943125575, message_ty...
          │            └ Bot(type='OneBot V11', self_id='1070330078')
          └ <function _check_reply at 0x7ff1040ac7c0>
> File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/bot.py", line 34, in _check_reply
    event.reply = Reply.parse_obj(await bot.get_msg(message_id=msg_seg.data["id"]))
    │     │       │     │               │                      │       └ {'id': 3181547}
    │     │       │     │               │                      └ MessageSegment(type='reply', data={'id': 3181547})
    │     │       │     │               └ Bot(type='OneBot V11', self_id='1070330078')
    │     │       │     └ <classmethod(<cyfunction BaseModel.parse_obj at 0x7ff1047d8450>)>
    │     │       └ <class 'nonebot.adapters.onebot.v11.event.Reply'>
    │     └ None
    └ GroupMessageEvent(time=1696915658, self_id=1070330078, post_type='message', sub_type='normal', user_id=1943125575, message_ty...
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
          └ ActionFailed(status='failed', retcode=35000, data={}, message='Obtain msg failed, please check your msg_id.', echo='41')
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'message_id': 3181547}
                   │    │       │         │     └ 'get_msg'
                   │    │       │         └ Bot(type='OneBot V11', self_id='1070330078')
                   │    │       └ <function Adapter._call_api at 0x7ff1040af600>
                   │    └ Adapter(name='OneBot V11')
                   └ Bot(type='OneBot V11', self_id='1070330078')
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 143, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
           │                       │    │             │     │    └ 30.0
           │                       │    │             │     └ 41
           │                       │    │             └ <function ResultStore.fetch at 0x7ff1040af380>
           │                       │    └ <nonebot.adapters.onebot.store.ResultStore object at 0x7ff1040da310>
           │                       └ Adapter(name='OneBot V11')
           └ <function handle_api_result at 0x7ff104035080>
  File "/home/admin/bots/SneakyBot/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
          │              └ {'status': 'failed', 'retcode': 35000, 'data': {}, 'message': 'Obtain msg failed, please check your msg_id.', 'echo': '41'}
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=35000, data={}, message='Obtain msg failed, please check your msg_id.', echo='41')
2023-10-10 13:27:38.420 | SUCCESS  | nonebot:handle_event:497 - OneBot V11 1070330078 | [message.group.normal]: Message 1435008350 from 1943125575@[群:xxxxx] '[reply:id=3181547]456'
```
是否可能是 reply 的 id 与记录的消息不一致？

**Comment by Well2333** [comment]
![image](https://github.com/linxinrao/Shamrock/assets/40534114/abc28434-05ec-4e40-85e7-aedb3ecea6ae)
我查询了日志，发现全部 reply id 均为 3181547
