### ISSUE TITLE
bug: 群荣誉获取闪退

### ISSUE THREAD

**Issue by fuqiuluo** [linxinrao/Shamrock#95]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/linxinrao/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

请清晰地描述此 Bug 的具体表现，并提供错误日志。

### 复现 Bug

请提供复现 Bug 的详细步骤，以确保我们可以理解并定位问题。

## 系统信息

- Shamrock 版本: 1.0.4
- Android 版本: ALL
- 设备的制造商和型号: ALL
- 设备的 CPU 架构: ALL

**Comment by RealHeart** [comment]
```log
java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION: java_class == null
java_vm_ext.cc:594]     in call to GetMethodID
java_vm_ext.cc:594]     from moe.fuqiuluo.shamrock.remote.service.data.GroupMemberHonor moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.nativeDecodeHonor(java.lang.String, int, byte)
runtime.cc:675] Runtime aborting...
runtime.cc:675] Dumping all threads without mutator lock held
runtime.cc:675] All threads:
runtime.cc:675] DALVIK THREADS (318):
runtime.cc:675] "eventLoopGroupProxy-4-2" prio=5 tid=317 Runnable
runtime.cc:675]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x14544780 self=0x71e847d400
runtime.cc:675]   | sysTid=16987 nice=0 cgrp=top-app sched=0/0 handle=0x70e1ce9cb0
runtime.cc:675]   | state=R schedstat=( 15797240 0 4 ) utm=1 stm=0 core=6 HZ=100
runtime.cc:675]   | stack=0x70e1be6000-0x70e1be8000 stackSize=1039KB
runtime.cc:675]   | held mutexes= "abort lock" "mutator lock"(shared held)
runtime.cc:675]   native: #00 pc 0000000000564a50  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+152) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #01 pc 0000000000668148  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+344) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #02 pc 00000000006855c8  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+912) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #03 pc 000000000067f3e0  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+508) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #04 pc 000000000067e6ac  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1824) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #05 pc 00000000006349b8  /apex/com.android.art/lib64/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+216) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #06 pc 000000000061f148  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1272) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #07 pc 0000000000017114  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+84) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
runtime.cc:675]   native: #08 pc 0000000000016648  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+356) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
runtime.cc:675]   native: #09 pc 0000000000459d44  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2368) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #10 pc 00000000004712e4  /apex/com.android.art/lib64/libart.so (art::JNI<false>::GetMethodID(_JNIEnv*, _jclass*, char const*, char const*)+1328) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #11 pc 00000000000bb704  /data/app/~~3bC7PE8h2DHf6pFmZBsi4w==/moe.fuqiuluo.shamrock-SawecRJSoC5PuEmwhqUpBQ==/lib/arm64/libshamrock.so (_JNIEnv::GetMethodID(_jclass*, char const*, char const*)+52) (BuildId: bdd5b3e6951a5c462c7ce2a56f7567354f36318f)
runtime.cc:675]   native: #12 pc 00000000000bb41c  /data/app/~~3bC7PE8h2DHf6pFmZBsi4w==/moe.fuqiuluo.shamrock-SawecRJSoC5PuEmwhqUpBQ==/lib/arm64/libshamrock.so (make_honor_object(_JNIEnv*, _jobject*, Honor const&)+68) (BuildId: bdd5b3e6951a5c462c7ce2a56f7567354f36318f)
runtime.cc:675]   native: #13 pc 00000000000babbc  /data/app/~~3bC7PE8h2DHf6pFmZBsi4w==/moe.fuqiuluo.shamrock-SawecRJSoC5PuEmwhqUpBQ==/lib/arm64/libshamrock.so (Java_moe_fuqiuluo_shamrock_remote_action_handlers_GetTroopHonor_nativeDecodeHonor+1456) (BuildId: bdd5b3e6951a5c462c7ce2a56f7567354f36318f)
runtime.cc:675]   native: #14 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #15 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #16 pc 00000000001b1e14  [anon:dalvik-DEX data] (moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke+440)
runtime.cc:675]   native: #17 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #18 pc 00000000001b1c40  [anon:dalvik-DEX data] (moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke$default+20)
runtime.cc:675]   native: #19 pc 0000000000209b68  /apex/com.android.art/lib64/libart.so (nterp_helper+2152) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #20 pc 00000000001745f8  [anon:dalvik-DEX data] (moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invokeSuspend+316)
runtime.cc:675]   native: #21 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #22 pc 000000000017447a  [anon:dalvik-DEX data] (moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke+18)
runtime.cc:675]   native: #23 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #24 pc 00000000001744a0  [anon:dalvik-DEX data] (moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke+12)
runtime.cc:675]   native: #25 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #26 pc 0000000000fdf784  [anon:dalvik-DEX data] (io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend+124)
runtime.cc:675]   native: #27 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #28 pc 0000000000fdf6c6  [anon:dalvik-DEX data] (io.ktor.server.routing.Route$buildPipeline$1$1.invoke+26)
runtime.cc:675]   native: #29 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #30 pc 0000000000fdf6ec  [anon:dalvik-DEX data] (io.ktor.server.routing.Route$buildPipeline$1$1.invoke+12)
runtime.cc:675]   native: #31 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #32 pc 0000000000fe9daa  [anon:dalvik-DEX data] (io.ktor.util.pipeline.SuspendFunctionGun.loop+98)
runtime.cc:675]   native: #33 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #34 pc 0000000000fe9eae  [anon:dalvik-DEX data] (io.ktor.util.pipeline.SuspendFunctionGun.proceed+50)
runtime.cc:675]   native: #35 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #36 pc 0000000000fe9e3a  [anon:dalvik-DEX data] (io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils+38)
runtime.cc:675]   native: #37 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #38 pc 0000000000fe8fd8  [anon:dalvik-DEX data] (io.ktor.util.pipeline.Pipeline.execute+16)
runtime.cc:675]   native: #39 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #40 pc 0000000000fe0b64  [anon:dalvik-DEX data] (io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend+76)
runtime.cc:675]   native: #146 pc 00000000002da1e8  [anon:dalvik-DEX data] (io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead+68)
runtime.cc:675]   native: #147 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #148 pc 00000000002d9eb4  [anon:dalvik-DEX data] (io.netty.channel.AbstractChannelHandlerContext.access$600)
runtime.cc:675]   native: #149 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #150 pc 00000000002d8b58  [anon:dalvik-DEX data] (io.netty.channel.AbstractChannelHandlerContext$7.run+8)
runtime.cc:675]   native: #151 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #152 pc 00000000003d6720  [anon:dalvik-DEX data] (io.netty.util.concurrent.AbstractEventExecutor.runTask)
runtime.cc:675]   native: #153 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #154 pc 00000000003d6738  [anon:dalvik-DEX data] (io.netty.util.concurrent.AbstractEventExecutor.safeExecute)
runtime.cc:675]   native: #155 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #156 pc 00000000003dd96a  [anon:dalvik-DEX data] (io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks+58)
runtime.cc:675]   native: #157 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #158 pc 0000000000309e3a  [anon:dalvik-DEX data] (io.netty.channel.nio.NioEventLoop.run+334)
runtime.cc:675]   native: #159 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #160 pc 00000000003dc8a4  [anon:dalvik-DEX data] (io.netty.util.concurrent.SingleThreadEventExecutor$4.run+104)
runtime.cc:675]   native: #161 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #162 pc 00000000003ea234  [anon:dalvik-DEX data] (io.netty.util.internal.ThreadExecutorMap$2.run+16)
runtime.cc:675]   native: #163 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #164 pc 0000000000fc7ed2  [anon:dalvik-DEX data] (io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0+10)
runtime.cc:675]   native: #165 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #166 pc 0000000000fc7e80  [anon:dalvik-DEX data] (io.ktor.server.netty.EventLoopGroupProxy$Companion.$r8$lambda$XgnKz7L6tCWRUaIAa7SVURwtFE4)
runtime.cc:675]   native: #167 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #168 pc 0000000000fc7cb8  [anon:dalvik-DEX data] (io.ktor.server.netty.EventLoopGroupProxy$Companion$$ExternalSyntheticLambda1.run+4)
runtime.cc:675]   native: #169 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.nativeDecodeHonor(Native method)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke(GetTroopHonor.kt:31)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke$default(GetTroopHonor.kt:23)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invokeSuspend(GroupAction.kt:24)
runtime.cc:675]   native: #170 pc 000000000021096c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #171 pc 000000000027b478  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #172 pc 00000000006182b4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+464) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #173 pc 00000000006605cc  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1292) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
runtime.cc:675]   native: #174 pc 00000000000f55c8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 449f781894033dce6346794a1ee593e0)
runtime.cc:675]   native: #175 pc 000000000008efbc  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 449f781894033dce6346794a1ee593e0)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.nativeDecodeHonor(Native method)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke(GetTroopHonor.kt:31)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke$default(GetTroopHonor.kt:23)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invokeSuspend(GroupAction.kt:24)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke(unavailable:9)
runtime.cc:675]   at moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke(unavailable:6)
runtime.cc:675]   at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
runtime.cc:675]   at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(unavailable:13)
runtime.cc:675]   at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(unavailable:6)
runtime.cc:675]   at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
runtime.cc:675]   at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
runtime.cc:675]   at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
runtime.cc:675]   at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
runtime.cc:675]   at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
runtime.cc:675]   at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(unavailable:8)
runtime.cc:675]   at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(unavailable:2)
runtime.cc:675]   at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
runtime.cc:675]   at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
runtime.cc:675]   at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
runtime.cc:675]   at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
runtime.cc:675]   at io.ktor.server.routing.Routing$Plugin$install$1.invoke(unavailable:11)
runtime.cc:675]   at io.ktor.server.routing.Routing$Plugin$install$1.invoke(unavailable:6)
runtime.cc:675]   at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
runtime.cc:675]   at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
runtime.cc:675]   at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
runtime.cc:675]   at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(unavailable:9)
runtime.cc:675]   at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(unavailable:6)
runtime.cc:683] JNI DETECTED ERROR IN APPLICATION: java_class == null
runtime.cc:683]     in call to GetMethodID
runtime.cc:683]     from moe.fuqiuluo.shamrock.remote.service.data.GroupMemberHonor moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.nativeDecodeHonor(java.lang.String, int, byte)
java.lang.ClassNotFoundException: Didn't find class "moe.qqinterface.service.data.GroupMemberHonor" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, 491790104064, 491790104256, 491790104448, 491790104640, 491790104832, 491790105024, 491790105216, 491790105408, 491790105600, 491790105792, 491790105984, 491790106176, 491790106368, 491790106560, 491790106752, 491790106944, 491790107136, 491790107328, 491790107520, 491790107712, 491790107904, 491790108096, 491790108288, 491790108480, 491790108672]]"],nativeLibraryDirectories=[/data/app/~~3bC7PE8h2DHf6pFmZBsi4w==/moe.fuqiuluo.shamrock-SawecRJSoC5PuEmwhqUpBQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.nativeDecodeHonor(Native Method)
	at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke(GetTroopHonor.kt:31)
	at moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke$default(GetTroopHonor.kt:23)
getCrashExtraMessage isNativeCrashed=true, crashType=SIGABRT, crashAddress=0x289500003ed9, crashStack=#00    pc 000000000008d774    /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) [arm64-v8a::449f781894033dce6346794a1ee593e0]
#01    pc 0046c3f2b5a1f104    <unknown>
java pending exception:
[Native crash above happened with a Java pending exception as following]
java.lang.ClassNotFoundException: Didn't find class "moe.qqinterface.service.data.GroupMemberHonor" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, 491790104064, 491790104256, 491790104448, 491790104640, 491790104832, 491790105024, 491790105216, 491790105408, 491790105600, 491790105792, 491790105984, 491790106176, 491790106368, 491790106560, 491790106752, 491790106944, 491790107136, 491790107328, 491790107520, 491790107712, 491790107904, 491790108096, 491790108288, 491790108480, 491790108672]]"],nativeLibraryDirectories=[/data/app/~~3bC7PE8h2DHf6pFmZBsi4w==/moe.fuqiuluo.shamrock-SawecRJSoC5PuEmwhqUpBQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
l0.loadClass(Unknown Source:18)
java.lang.ClassLoader.loadClass(ClassLoader.java:312)
moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.nativeDecodeHonor(Native Method)
moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke(GetTroopHonor.kt:31)
moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke$default(GetTroopHonor.kt:23)
moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invokeSuspend(GroupAction.kt:24)
moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke(Unknown Source:9)
moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke(Unknown Source:6)
io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Unknown Source:13)
io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Unknown Source:6)
io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Unknown Source:8)
io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Unknown Source:2)
io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
io.ktor.server.routing.Routing$Plugin$install$1.invoke(Unknown Source:11)
io.ktor.server.routing.Routing$Plugin$install$1.invoke(Unknown Source:6)
io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(Unknown Source:9)
io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(Unknown Source:6)
io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
io.ktor.server.application.hooks.CallFailed$install$1$1.invokeSuspend(CommonHooks.kt:45)
io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(Unknown Source:8)
io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(Unknown Source:4)
kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
io.ktor.server.application.hooks.CallFailed$install$1.invokeSuspend(CommonHooks.kt:44)
io.ktor.server.application.hooks.CallFailed$install$1.invoke(Unknown Source:11)
io.ktor.server.application.hooks.CallFailed$install$1.invoke(Unknown Source:6)
io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Unknown Source:8)
io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Unknown Source:2)
io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:123)
io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(Unknown Source:9)
io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(Unknown Source:6)
io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Unknown Source:8)
io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Unknown Source:2)
io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
io.ktor.server.netty.NettyAppli

[Java stack is truncated for it exceeds the max size.]
java:
moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke(GetTroopHonor.kt:31)
moe.fuqiuluo.shamrock.remote.action.handlers.GetTroopHonor.invoke$default(GetTroopHonor.kt:23)
moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invokeSuspend(GroupAction.kt:24)
moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke(Unknown Source:9)
moe.fuqiuluo.shamrock.remote.api.GroupActionKt$troopAction$2.invoke(Unknown Source:6)
io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Unknown Source:13)
io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Unknown Source:6)
io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Unknown Source:8)
io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Unknown Source:2)
io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
io.ktor.server.routing.Routing$Plugin$install$1.invoke(Unknown Source:11)
io.ktor.server.routing.Routing$Plugin$install$1.invoke(Unknown Source:6)
io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
--------- beginning of crash
```
